export interface MedDBItem {
  name: string;
  form: string;
  strength: string;
  adultDose: string;
  pediatricDose?: string;
}

export const MEDICINE_DB: MedDBItem[] = [
  // Analgesics & Antipyretics
  { name: 'Paracetamol', form: 'Tablet', strength: '500mg', adultDose: '1 tab', pediatricDose: '10-15 mg/kg/dose' },
  { name: 'Paracetamol', form: 'Tablet', strength: '650mg', adultDose: '1 tab', pediatricDose: '10-15 mg/kg/dose' },
  { name: 'Paracetamol', form: 'Syrup', strength: '250mg/5ml', adultDose: '10ml', pediatricDose: '10-15 mg/kg/dose' },
  { name: 'Paracetamol', form: 'Syrup', strength: '125mg/5ml', adultDose: '10ml', pediatricDose: '10-15 mg/kg/dose' },
  { name: 'Paracetamol', form: 'Drops', strength: '100mg/ml', adultDose: '-', pediatricDose: '10-15 mg/kg/dose' },
  { name: 'Ibuprofen', form: 'Tablet', strength: '400mg', adultDose: '1 tab', pediatricDose: '5-10 mg/kg/dose' },
  { name: 'Ibuprofen', form: 'Syrup', strength: '100mg/5ml', adultDose: '10ml', pediatricDose: '5-10 mg/kg/dose' },
  { name: 'Diclofenac', form: 'Tablet', strength: '50mg', adultDose: '1 tab', pediatricDose: 'Not recommended' },
  { name: 'Diclofenac', form: 'Injection', strength: '75mg/ml', adultDose: '1 amp IM', pediatricDose: 'Not recommended' },
  { name: 'Aceclofenac', form: 'Tablet', strength: '100mg', adultDose: '1 tab', pediatricDose: 'Not recommended' },
  { name: 'Aceclofenac + Paracetamol', form: 'Tablet', strength: '100mg+325mg', adultDose: '1 tab', pediatricDose: 'Not recommended' },
  { name: 'Naproxen', form: 'Tablet', strength: '250mg', adultDose: '1 tab', pediatricDose: '5-7 mg/kg/dose' },
  { name: 'Naproxen', form: 'Tablet', strength: '500mg', adultDose: '1 tab', pediatricDose: '5-7 mg/kg/dose' },
  { name: 'Tramadol', form: 'Tablet', strength: '50mg', adultDose: '1 tab', pediatricDose: 'Not recommended' },
  { name: 'Ketorolac', form: 'Tablet', strength: '10mg', adultDose: '1 tab', pediatricDose: 'Not recommended' },
  { name: 'Mefenamic Acid', form: 'Tablet', strength: '250mg', adultDose: '1 tab', pediatricDose: '4-6 mg/kg/dose' },
  { name: 'Mefenamic Acid', form: 'Syrup', strength: '100mg/5ml', adultDose: '10ml', pediatricDose: '4-6 mg/kg/dose' },

  // Antibiotics
  { name: 'Amoxicillin', form: 'Capsule', strength: '250mg', adultDose: '1 cap', pediatricDose: '40-45 mg/kg/day' },
  { name: 'Amoxicillin', form: 'Capsule', strength: '500mg', adultDose: '1 cap', pediatricDose: '40-45 mg/kg/day' },
  { name: 'Amoxicillin', form: 'Syrup', strength: '125mg/5ml', adultDose: '10ml', pediatricDose: '40-45 mg/kg/day' },
  { name: 'Amoxiclav (Amoxicillin+Clavulanate)', form: 'Tablet', strength: '625mg', adultDose: '1 tab', pediatricDose: '40-45 mg/kg/day' },
  { name: 'Amoxiclav', form: 'Tablet', strength: '375mg', adultDose: '1 tab', pediatricDose: '40-45 mg/kg/day' },
  { name: 'Amoxiclav', form: 'Syrup', strength: '228.5mg/5ml', adultDose: '5ml', pediatricDose: '40-45 mg/kg/day' },
  { name: 'Azithromycin', form: 'Tablet', strength: '250mg', adultDose: '1 tab', pediatricDose: '10 mg/kg/day' },
  { name: 'Azithromycin', form: 'Tablet', strength: '500mg', adultDose: '1 tab', pediatricDose: '10 mg/kg/day' },
  { name: 'Azithromycin', form: 'Syrup', strength: '200mg/5ml', adultDose: '5ml', pediatricDose: '10 mg/kg/day' },
  { name: 'Azithromycin', form: 'Syrup', strength: '100mg/5ml', adultDose: '5ml', pediatricDose: '10 mg/kg/day' },
  { name: 'Cefixime', form: 'Tablet', strength: '200mg', adultDose: '1 tab', pediatricDose: '8 mg/kg/day' },
  { name: 'Cefixime', form: 'Syrup', strength: '100mg/5ml', adultDose: '5ml', pediatricDose: '8 mg/kg/day' },
  { name: 'Cefixime', form: 'Syrup', strength: '50mg/5ml', adultDose: '5ml', pediatricDose: '8 mg/kg/day' },
  { name: 'Cefpodoxime', form: 'Tablet', strength: '200mg', adultDose: '1 tab', pediatricDose: '10 mg/kg/day' },
  { name: 'Cefpodoxime', form: 'Syrup', strength: '50mg/5ml', adultDose: '5ml', pediatricDose: '10 mg/kg/day' },
  { name: 'Ceftriaxone', form: 'Injection', strength: '1g', adultDose: '1 vial IV/IM', pediatricDose: '50-75 mg/kg/day' },
  { name: 'Ciprofloxacin', form: 'Tablet', strength: '500mg', adultDose: '1 tab', pediatricDose: 'Not recommended' },
  { name: 'Levofloxacin', form: 'Tablet', strength: '500mg', adultDose: '1 tab', pediatricDose: 'Not recommended' },
  { name: 'Ofloxacin', form: 'Tablet', strength: '200mg', adultDose: '1 tab', pediatricDose: '15 mg/kg/day' },
  { name: 'Metronidazole', form: 'Tablet', strength: '400mg', adultDose: '1 tab', pediatricDose: '30 mg/kg/day' },
  { name: 'Metronidazole', form: 'Syrup', strength: '200mg/5ml', adultDose: '5ml', pediatricDose: '30 mg/kg/day' },
  { name: 'Doxycycline', form: 'Capsule', strength: '100mg', adultDose: '1 cap', pediatricDose: 'Not recommended <8 yrs' },
  { name: 'Linezolid', form: 'Tablet', strength: '600mg', adultDose: '1 tab', pediatricDose: '10 mg/kg/dose' },

  // Gastrointestinal
  { name: 'Pantoprazole', form: 'Tablet', strength: '40mg', adultDose: '1 tab', pediatricDose: '1 mg/kg/day' },
  { name: 'Pantoprazole', form: 'Injection', strength: '40mg', adultDose: '1 vial IV', pediatricDose: '1 mg/kg/day' },
  { name: 'Pantoprazole + Domperidone', form: 'Capsule', strength: '40mg+30mg SR', adultDose: '1 cap', pediatricDose: 'Not recommended' },
  { name: 'Rabeprazole', form: 'Tablet', strength: '20mg', adultDose: '1 tab', pediatricDose: 'Not recommended' },
  { name: 'Rabeprazole + Domperidone', form: 'Capsule', strength: '20mg+30mg SR', adultDose: '1 cap', pediatricDose: 'Not recommended' },
  { name: 'Omeprazole', form: 'Capsule', strength: '20mg', adultDose: '1 cap', pediatricDose: '1 mg/kg/day' },
  { name: 'Ranitidine', form: 'Tablet', strength: '150mg', adultDose: '1 tab', pediatricDose: '2-4 mg/kg/dose' },
  { name: 'Ondansetron', form: 'Tablet', strength: '4mg', adultDose: '1 tab', pediatricDose: '0.15 mg/kg/dose' },
  { name: 'Ondansetron', form: 'Syrup', strength: '2mg/5ml', adultDose: '10ml', pediatricDose: '0.15 mg/kg/dose' },
  { name: 'Domperidone', form: 'Tablet', strength: '10mg', adultDose: '1 tab', pediatricDose: '0.2-0.4 mg/kg/dose' },
  { name: 'Metoclopramide', form: 'Tablet', strength: '10mg', adultDose: '1 tab', pediatricDose: '0.1-0.15 mg/kg/dose' },
  { name: 'Loperamide', form: 'Capsule', strength: '2mg', adultDose: '1 cap', pediatricDose: 'Not recommended <2 yrs' },
  { name: 'ORS (Oral Rehydration Salts)', form: 'Sachet', strength: '21.8g', adultDose: '1 sachet in 1L water', pediatricDose: 'As per dehydration' },
  { name: 'Pre/Probiotics', form: 'Capsule', strength: 'Standard', adultDose: '1 cap', pediatricDose: '1 sachet/cap' },
  { name: 'Pre/Probiotics', form: 'Sachet', strength: 'Standard', adultDose: '1 sachet', pediatricDose: '1 sachet' },
  { name: 'Sucralfate', form: 'Syrup', strength: '1g/10ml', adultDose: '10ml', pediatricDose: 'Not recommended' },

  // Respiratory & Antiallergics
  { name: 'Cetirizine', form: 'Tablet', strength: '10mg', adultDose: '1 tab', pediatricDose: '0.25 mg/kg/day' },
  { name: 'Cetirizine', form: 'Syrup', strength: '5mg/5ml', adultDose: '10ml', pediatricDose: '0.25 mg/kg/day' },
  { name: 'Levocetirizine', form: 'Tablet', strength: '5mg', adultDose: '1 tab', pediatricDose: '0.125 mg/kg/day' },
  { name: 'Levocetirizine', form: 'Syrup', strength: '2.5mg/5ml', adultDose: '10ml', pediatricDose: '0.125 mg/kg/day' },
  { name: 'Chlorpheniramine', form: 'Tablet', strength: '4mg', adultDose: '1 tab', pediatricDose: '0.35 mg/kg/day' },
  { name: 'Montelukast', form: 'Tablet', strength: '10mg', adultDose: '1 tab', pediatricDose: '4-5 mg/day' },
  { name: 'Montelukast + Levocetirizine', form: 'Tablet', strength: '10mg+5mg', adultDose: '1 tab', pediatricDose: 'Not recommended <15 yrs' },
  { name: 'Montelukast', form: 'Tablet (Chewable)', strength: '5mg', adultDose: '-', pediatricDose: '1 tab (6-14 yrs)' },
  { name: 'Montelukast', form: 'Tablet (Chewable)', strength: '4mg', adultDose: '-', pediatricDose: '1 tab (2-5 yrs)' },
  { name: 'Salbutamol', form: 'Tablet', strength: '2mg', adultDose: '1 tab', pediatricDose: '0.1-0.15 mg/kg/dose' },
  { name: 'Salbutamol', form: 'Syrup', strength: '2mg/5ml', adultDose: '5-10ml', pediatricDose: '0.1-0.15 mg/kg/dose' },
  { name: 'Salbutamol', form: 'Inhaler', strength: '100mcg/puff', adultDose: '2 puffs', pediatricDose: '1-2 puffs' },
  { name: 'Budesonide', form: 'Inhaler', strength: '200mcg/puff', adultDose: '2 puffs', pediatricDose: '1-2 puffs' },
  { name: 'Dextromethorphan', form: 'Syrup', strength: '10mg/5ml', adultDose: '10ml', pediatricDose: '1-2 mg/kg/day' },
  { name: 'Ambroxol', form: 'Syrup', strength: '30mg/5ml', adultDose: '10ml', pediatricDose: '1.2-1.6 mg/kg/day' },

  // Cardiovascular & BP
  { name: 'Amlodipine', form: 'Tablet', strength: '5mg', adultDose: '1 tab', pediatricDose: 'Not recommended' },
  { name: 'Amlodipine', form: 'Tablet', strength: '10mg', adultDose: '1 tab', pediatricDose: 'Not recommended' },
  { name: 'Telmisartan', form: 'Tablet', strength: '40mg', adultDose: '1 tab', pediatricDose: 'Not recommended' },
  { name: 'Telmisartan', form: 'Tablet', strength: '80mg', adultDose: '1 tab', pediatricDose: 'Not recommended' },
  { name: 'Telmisartan + Amlodipine', form: 'Tablet', strength: '40mg+5mg', adultDose: '1 tab', pediatricDose: 'Not recommended' },
  { name: 'Losartan', form: 'Tablet', strength: '50mg', adultDose: '1 tab', pediatricDose: 'Not recommended' },
  { name: 'Enalapril', form: 'Tablet', strength: '5mg', adultDose: '1 tab', pediatricDose: 'Not recommended' },
  { name: 'Metoprolol', form: 'Tablet', strength: '25mg', adultDose: '1 tab', pediatricDose: 'Not recommended' },
  { name: 'Metoprolol', form: 'Tablet', strength: '50mg', adultDose: '1 tab', pediatricDose: 'Not recommended' },
  { name: 'Atenolol', form: 'Tablet', strength: '50mg', adultDose: '1 tab', pediatricDose: 'Not recommended' },
  { name: 'Rosuvastatin', form: 'Tablet', strength: '10mg', adultDose: '1 tab', pediatricDose: 'Not recommended' },
  { name: 'Rosuvastatin', form: 'Tablet', strength: '20mg', adultDose: '1 tab', pediatricDose: 'Not recommended' },
  { name: 'Atorvastatin', form: 'Tablet', strength: '10mg', adultDose: '1 tab', pediatricDose: 'Not recommended' },
  { name: 'Atorvastatin', form: 'Tablet', strength: '20mg', adultDose: '1 tab', pediatricDose: 'Not recommended' },
  { name: 'Atorvastatin', form: 'Tablet', strength: '40mg', adultDose: '1 tab', pediatricDose: 'Not recommended' },
  { name: 'Clopidogrel', form: 'Tablet', strength: '75mg', adultDose: '1 tab', pediatricDose: 'Not recommended' },
  { name: 'Aspirin', form: 'Tablet', strength: '75mg', adultDose: '1 tab', pediatricDose: 'Not recommended' },
  { name: 'Aspirin', form: 'Tablet', strength: '150mg', adultDose: '1 tab', pediatricDose: 'Not recommended' },

  // Anti-diabetics
  { name: 'Metformin', form: 'Tablet', strength: '500mg', adultDose: '1 tab', pediatricDose: 'Not recommended' },
  { name: 'Metformin', form: 'Tablet', strength: '1000mg', adultDose: '1 tab', pediatricDose: 'Not recommended' },
  { name: 'Glimepiride', form: 'Tablet', strength: '1mg', adultDose: '1 tab', pediatricDose: 'Not recommended' },
  { name: 'Glimepiride', form: 'Tablet', strength: '2mg', adultDose: '1 tab', pediatricDose: 'Not recommended' },
  { name: 'Gliclazide', form: 'Tablet', strength: '80mg', adultDose: '1 tab', pediatricDose: 'Not recommended' },
  { name: 'Sitagliptin', form: 'Tablet', strength: '50mg', adultDose: '1 tab', pediatricDose: 'Not recommended' },
  { name: 'Sitagliptin', form: 'Tablet', strength: '100mg', adultDose: '1 tab', pediatricDose: 'Not recommended' },
  { name: 'Teneligliptin', form: 'Tablet', strength: '20mg', adultDose: '1 tab', pediatricDose: 'Not recommended' },
  { name: 'Dapagliflozin', form: 'Tablet', strength: '10mg', adultDose: '1 tab', pediatricDose: 'Not recommended' },

  // Vitamins & Supplements
  { name: 'Iron + Folic Acid', form: 'Tablet', strength: '100mg+1.5mg', adultDose: '1 tab', pediatricDose: 'As per weight' },
  { name: 'Iron + Folic Acid', form: 'Syrup', strength: '50mg+0.5mg/5ml', adultDose: '10ml', pediatricDose: 'As per weight' },
  { name: 'Calcium + Vitamin D3', form: 'Tablet', strength: '500mg+250IU', adultDose: '1 tab', pediatricDose: '1/2 tab' },
  { name: 'Vitamin C', form: 'Tablet', strength: '500mg', adultDose: '1 tab', pediatricDose: '1/2 tab' },
  { name: 'Zinc', form: 'Tablet', strength: '20mg', adultDose: '1 tab', pediatricDose: '10-20mg/day' },
  { name: 'Zinc', form: 'Syrup', strength: '20mg/5ml', adultDose: '5ml', pediatricDose: '10-20mg/day' },
  { name: 'Multivitamin', form: 'Tablet', strength: 'Standard', adultDose: '1 tab', pediatricDose: 'Not recommended' },
  { name: 'Multivitamin', form: 'Syrup', strength: 'Standard', adultDose: '10ml', pediatricDose: '5ml' },
  { name: 'B-Complex', form: 'Capsule', strength: 'Standard', adultDose: '1 cap', pediatricDose: 'Not recommended' },
  { name: 'Vitamin D3', form: 'Capsule', strength: '60K IU', adultDose: '1 cap weekly', pediatricDose: 'As per deficiency' },
  { name: 'Vitamin D3', form: 'Sachet', strength: '60K IU', adultDose: '1 sachet weekly', pediatricDose: 'As per deficiency' },

  // Anti-parasitic & Anti-fungal & Anti-viral
  { name: 'Albendazole', form: 'Tablet', strength: '400mg', adultDose: '1 tab stat', pediatricDose: '200-400mg stat' },
  { name: 'Albendazole', form: 'Syrup', strength: '200mg/5ml', adultDose: '10ml stat', pediatricDose: '5-10ml stat' },
  { name: 'Ivermectin', form: 'Tablet', strength: '12mg', adultDose: '1 tab', pediatricDose: '0.2 mg/kg' },
  { name: 'Fluconazole', form: 'Tablet', strength: '150mg', adultDose: '1 tab', pediatricDose: '3-6 mg/kg/day' },
  { name: 'Itraconazole', form: 'Capsule', strength: '100mg', adultDose: '1 cap', pediatricDose: 'Not recommended' },
  { name: 'Acyclovir', form: 'Tablet', strength: '400mg', adultDose: '1 tab', pediatricDose: '20 mg/kg/dose' },
  { name: 'Permethrin', form: 'Cream', strength: '5%', adultDose: 'Apply locally', pediatricDose: 'Apply locally' },
  
  // Topical / Others
  { name: 'Diclofenac Gel', form: 'Gel', strength: '1%', adultDose: 'Apply locally', pediatricDose: 'Apply locally' },
  { name: 'Mupirocin', form: 'Ointment', strength: '2%', adultDose: 'Apply locally', pediatricDose: 'Apply locally' },
  { name: 'Clotrimazole', form: 'Cream', strength: '1%', adultDose: 'Apply locally', pediatricDose: 'Apply locally' },
  { name: 'Povidone Iodine', form: 'Ointment', strength: '5%', adultDose: 'Apply locally', pediatricDose: 'Apply locally' },
];
